### ISSUE TITLE
clarification needed in alignRequests

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#101]
https://github.com/raintank/raintank-metric/blob/00411554d80427691246df4aa4290b9d5a782e0b/metric_tank/query_engine.go#L164-L167

* isn't maxDataPoints bigger than ptCount so `aggNum = ptCount / req.maxPoints` should be `aggNum = req.maxPoints / ptCount` I think.
* shouldn't `if ptCount%req.maxPoints != 0 {` be `ptCount%aggNum` ?
* i don't think aggNum++ guarantees a no-remainder division. in fact by increasing aggNum it's more likely that the aggregation won't be a perfect fit, I think. the previous code didn't do any enforcing for that case I believe, and allowed for consolidation to consolidate however many points remain at the end.

**Comment by woodsaj** [comment]
> isn't maxDataPoints bigger than ptCount so aggNum = ptCount / req.maxPoints should be aggNum = req.maxPoints / ptCount I think.

No. If we are performing runtimte consolidation it is because ptCount is greater the maxPoints.  If it was the reverse there would be no need to do consolidation.

> shouldn't if ptCount%req.maxPoints != 0 { be ptCount%aggNum ?

No.  We are simply checking to see if `ptCount/req.MaxPoints` had a remainder and if so, we need to increment the result.  This is essentially the same as doing `aggNum = ceil(ptCount/req.MaxPoints)`

> i don't think aggNum++ guarantees a no-remainder division. in fact by increasing aggNum it's more likely that the aggregation won't be a perfect fit, I think. the previous code didn't do any enforcing for that case I believe, and allowed for consolidation to consolidate however many points remain at the end.

??? aggNum is "how many points to consolidate together at runtime"

if ptCount is 15 and maxPoints in 10, then ptCount/maxPoints == 1.  If you just left this as is, then there would be no consolidation as aggNum (the number of points to consolidate together) is 1.  Instead, aggNum needs to be adjusted to 2, so that after consolidation the number of values is less then maxPoints.

**Comment by Dieterbe** [comment]
> No. If we are performing runtimte consolidation it is because ptCount is greater the maxPoints. If it was the reverse there would be no need to do consolidation.

the code has 2 cases where runtimeconsolidation is enabled:
1) we decided to go to a higher-res archive using the datapointsbelowratio heuristic. here ptCount > maxPoints and i presume this is the case you're referring to.
2) selected == 0 and we have multiple raw archives, so we set choseninterval to the least common multiple of all rawintervals, to find an interval that works for all series. here ptCount is not neccessarily bigger than maxDataPoints. it can definitely be smaller.  However i realized the code still seems to hold fine in that case (aggNum would be set to 0 and then incremented to 1 due to the remainder) so no problem.

> No. We are simply checking to see if ptCount/req.MaxPoints had a remainder and if so, we need to increment the result. This is essentially the same as doing aggNum = ceil(ptCount/req.MaxPoints)

ah, i was confused about what was the goal here.
