### ISSUE TITLE
MT: statsd gauges for primary status

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#108]
so we can visualize primary status across the cluster.
@ctdk afaik you were working on this? can i help?

**Comment by ctdk** [comment]
I was working on it, yeah. There's a branch here: https://github.com/raintank/raintank-metric/tree/primary_status

I hadn't made a PR yet because I haven't subjected that to much testing, and what with your ankle related accident and the general hubbub around metric_tank lately I held off pushing hard on that. (I did bring it up on slack, but I think it was right around the time you got injured.)

**Comment by Dieterbe** [comment]
this looks fine to me, i suggest you create a PR for this. let's get this in!
