### ISSUE TITLE
why synchronous backfill?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#116]
https://github.com/raintank/raintank-metric/commit/e9f7088097749e5f4c2299e5c44f95b874a0a173

@woodsaj  did you see the comment:
```
// backfill definitions from ES
// in theory, there is a race between defs from ES and from nsq
// in practice, it doesn't matter: you're only supposed to query MT
// after a while, after which the defs surely have stabilized.
```

by making this synchronous we can't reliably know when MT starts ingesting metrics and from which point it's guaranteed to have all data (it'll start building up an nsq queue which may last until after backfill is complete, after which the effects of processing the queue will still be visible: metrics may not make it in at all because they get dropped due to out of order), which is problem since we need to know from where it has data so that we can make it primary. in the best case it's just an additional delay (until we see the last metric dropped message) but this means additional operator overhead.

if we keep it async we know it can start processing the nsq queue from immediately after startup, normally without dropping messages. there may be some race conditions between stale defs from ES and newer defs from nsq but in practice it doesn't matter as the metricdefcache will stabilize to the latest defs before the MT instance receives any queries.

**Comment by woodsaj** [comment]
The metricDefs need to be loaded from ES before we start consuming metrics from ES.  Otherwise every metric received prior to the metricDefs being loaded will get re-indexed to ES.  This puts a lot of load on ES and also invalidates the data loaded from ES. 

If this acceptable, then we may as well not load the metricDefs from ES at all. And instead just index every metric when we first see it (using the bulkAPI ) and then query for missing metricDefs when needed to serve queries.

**Comment by woodsaj** [comment]
@Dieterbe any further thoughts here?

**Comment by Dieterbe** [comment]
i like your point of why it makes sense to synchronously pull in the data first.
i've been working on a change that makes it clear to the MT operator at which point it'll start safely pulling in data, see https://github.com/raintank/raintank-metric/pull/135 but i still have to test it.
