### ISSUE TITLE
usage accounting

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-metric#188]
we need to keep track of the rate of metrics and number of series being written by each Org.

**Comment by Dieterbe** [comment]
I'm thinking:
* unique keys seen last 5min, every 5min
* points seen last 5min, every 5min.
storing that in graphite and we can get the mean or a percentile or whatever each month.

one thing that's still an open discussion is which of these two options is best:

build into metric-tank or separate service consuming from nsq/kafka?
basically microservice benefits, easy deployability etc vs extra bandwidth needed, extra service to monitor etc.
i think i'm going to add it to MT to start and see how far that takes us

another thing is what happens if we suffer a degradation/outage and we store is actually different.
maybe we could track metrics saved in MT on a per org level. otherwise those situations will be dealt with manually.

**Comment by woodsaj** [comment]
I would prefer to have the accounting built into MT.

> another thing is what happens if we suffer a degradation/outage and we store is actually different.
If we drop usage data the customer just gets a discount, which is acceptable.

The only problem is of we store usage data, but fail to store the customers metrics which **should** be extremely rare.  
If we write the usage data into MT under the customer's org, we can mostly avoid this. Any major outage that prevents customer data from being stored will also prevent usage data from being stored.  The added benefit of storing the usage data within the customers hostedTSDB account is that they can query this data out into their own grafana.

> maybe we could track metrics saved in MT on a per org level.
We have to store on a per Org level, else how would be know the usage of each org?

**Comment by Dieterbe** [comment]
this is merged now.
design limitation:
* data is accounted for based on how it comes into NSQ. i.e. subject to fluctuations due to buffering, and once we have kafka, to replaying data. better would be to make it true to ingest workload. this would be a good next step.
