### ISSUE TITLE
should all tags have user defined keys?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#20]
this is the continuation of a topic that started at https://github.com/raintank/raintank-metric/issues/11#issuecomment-132522012 (first point)
  then read https://github.com/raintank/raintank-metric/issues/11#issuecomment-132906748 and the few comments afterwards.

i basically suggested it might make sense to drop the requirement that all tags have a key defined at the origin (statsd calls etc)

i can't come up with an example where finding a tag-key is impossible or really hard but I think that's not the point.
i know i've had it in the past working in vimeo's backend code (to which i no longer have access) where a lot of stuff was going on and the systems had a lot of considerations before deciding on actions. we were instrumenting those actions (and the considerations that let up to them) so had a lot of metric dimensionality and while you would be able to come up with keys for all dimensions, they increased the length of the statsd invocations and the amount of work you had to do (typing and also thinking about wording and semantics). if you were creating tens of metrics, this was annoying.

on the other hand, not typing out keys in the instrumentation code and just using auto assigned tag keys was fine because you'd first search for the data and then drill down using the keys that the dashboard tells you it has auto-assigned (n1, n2, n3, ...)

so it's more about "it can be easier, sometimes people just want to go from A to B as quickly as possible", not "it's a must because of technical reasons"
I think @torkelo also has an opinion on this, he mentioned the other day a dowside of tag based systems (compared to graphite for example) is having to type out tag keys.

i know that @jedi4ever also mentioned an appreciation for the no-key-enforced approach of datadog, letting him just tag "staging", "production" etc instead of having to prefix with "environment:"

**Comment by woodsaj** [comment]
The problem i have with single strings is that it makes querying via Elasitcsearch much more difficult and less intuitive.  Elasticsearch will already tokenize the document, splitting on whitespace and other common deliminators like ":=,"

Eg.
With the following example documents

```
{
  "title": "Doc1",
  "tags": [
    "key1=foo1",
    "key2=foo2"
  ]
},
{
  "title": "Doc2",
  "tags": [
    "key5=foo1",
    "key2=foo3"
  ]
},
{
  "title": "Doc3",
  "tags": [
    "foobar"
  ]
},
{
  "title": "Doc4",
  "tags": [
    "key1=foo1",
    "key1=bar2"
  ]
},

```

if i wanted to match every document where key1==foo1, then i would need to quote my search query.
```
{
  "query": {
    "query_string": {
        "query": "tags:\"key1=foo1\""
    }
  }
}
```
which would match documents 1 and 4

The gotcha here, is that if you dont provide the quotes, the search will match all documents that have a tag that contains "key1" or "foo1", matching documents 1,2 and 4. This is certainly not the intended result.

Additionally because of the quoting, you lose the ability to do partial matches, ie, where the value of key "key2" starts with "foo".

However, as a benefit, if you just provided a search query of "tags:foo1" it would return all documents that have a tag that has a key or a value set to "foo1" 

with a key:value schema

```
{
  "title": "Doc1",
  "tags": {
    "key1": "foo1",
    "key2": "foo2"
  }
},
{
  "title": "Doc2",
  "tags": {
    "key5": "foo1",
    "key2": "foo3"
  }
},
{
  "title": "Doc3",
  "tags": 
    "foobar": "true"
  }
},
{
  "title": "Doc4",
  "tags": {
    "key1": "foo1 bar2",
  ]
},
```

The same search query to match where key1==foo1 becomes

```
{
  "query": {
    "query_string": {
        "query": "tags.key1:foo1"
    }
  }
}
```
No quoting necessary.

to match where key2 starts with foo
```
 "query": "tags.key2:foo*"
```

It would not be possible (to my knowledge) to send a query that would match either the key or the value.  But you can match the value across all keys by including a "fields" field to limit the scope of the query.
```
{
  "query": {
    "query_string": {
       "fields": ["tags.*"],
       "query": "foo1"
    }
  }
}
```
which would match documents 1, 2 and 4

Including the "fields" field on all queries would probably be a good practice anyway and wouldnt affect tag.key:value format queries

**Comment by woodsaj** [comment]
ok. So i have been reading up on this and experimenting with Elasticsearch, and it is looking more and more like single strings with ":" separated key value pairs is easiest to deal with.

As noted in the previous comments, when using an Object approach for key:value pairs, it is not possible to search where the key matches the query string.  This is a pretty big issue given that any UI would want to provide suggestions as users enter the query.

Turns out the default tokenizer in Elasticsearch wont split on ":" characters so "key:value" will be treated as 1 term, where as "key=value" would be treated as 2 ["key", "value"].   users would still be able to match a query across all keys by searching  "*:value" (the ':' needs to be escaped)

```
{  
  "query": {  
    "query_string": {  
      "fields": [ "tags" ],
      "query": "*\\:foo1"
    }
  }
}
```

**Comment by Dieterbe** [comment]
ok so you're saying we would store tags as an array of strings like "key:val" instead of using "=" ?

does this hamper or reinforce the feasability of key-less tags, and why?

**Comment by woodsaj** [comment]
So yes, i am saying stick with an array of strings.  Splitting the string into key/value pairs would be left up to the client querying the index (graphite/grafana).  Though for simplicity it using a colon ":" as the deliminator is the preferred approach.

This approach will allow users to use key-less tags.  Using key-less tags will however limit capabilities as the user wont be able to perform groupBy, AliasBy etc.. style transformations.

**Comment by Dieterbe** [comment]
okay. so actionable items?
* move to `[]string` instead of a map and use `:` as delimiter?

probably best if we can also put this change as part of the nsq migration.

**Comment by woodsaj** [comment]
yes.  ill update the collectors so they send strings.

**Comment by torkelo** [comment]
comment to mark this as answered in codetree

**Comment by woodsaj** [comment]
this has already been deployed to production. Metric definitions and events are using []string for tags.
