### ISSUE TITLE
redis-cluster support

### ISSUE THREAD

**Issue by ctdk** [raintank/raintank-metric#28]
To be able to use redis-cluster with `nsq_metrics_to_elasticsearch`, metricdefs needs to be updated to use `gopkg.in/redis.v3`. Additionally, the redis Client object will need to be a redis ClusterClient object (http://godoc.org/gopkg.in/redis.v3#ClusterClient).

Ideally there should be a config option to choose between normal redis and redis cluster. The redis address arguments need changed anyway to handle the cluster case.

**Comment by Dieterbe** [comment]
do we use redis for anything else but caching metricdefs?
if not, i'ld rather just do away with redis and just do ram-based caching/groupcache/...

**Comment by woodsaj** [comment]
redis is only needed as a cache for metricdefs

The decision on using redis was because we wanted a clustered memory based cache that supports replication and sharding to ensure the cache is always available.  The cache is a buffer to reduce load on Elasticsearch.  If we just use an in-memory cache, like groupcache, nsq_metrics_to_elastic service restarts then the cache is lost and a very large volume of reads will need to be processed by elasticsearch.  Previously, we were consistently routing metrics to the same node so this posed a greater problem.  But with metrics now being randomly distributed between all nodes this may be less of a problem.

**Comment by ctdk** [comment]
The only consideration is that we'll need to see how the cache items get spread around with groupcache. With consistent routing obviously they never made it anywhere, but we'll need to see how quickly keys can be redistributed if one is restarted, because if it takes too long it could make upgrades interesting.

**Comment by Dieterbe** [comment]
the other problems with groupcache are:
* no versioned values. we need to have a higher level key-scheme to assure values get updated, in a uniform volume over time (not hard, but just saying it's a thing)
* if we're going to rely on the keys being randomly spread around as a means to prevent thundering herd problems then every single cache effectively needs to contain *all* cache data. this approach only works until we max out our RAM on each node.

a scheme of sharding with replication seems like a better architectural fit indeed.
so let's just stick to redis-cluster.

**Comment by Dieterbe** [comment]
closing this as we're not using redis anymore at all. see #104
