### ISSUE TITLE
tank chunk keeping vs clearing, GC, refactoring

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#47]
because of these facts
1) Go's VM does not release memory to the kernel once allocated, even if the data has been cleared. it'll just keep the memory to reuse it when it needs it.
2) tank uses a circular buffer with a consistent size
3) it's always nice to be able to serve more data out of RAM especially if the cost is very low.

.. i figured we can hold on to any chunks occupying a slot in the circular buffer unless we need to force an eviction (newer data needs to reuse the slot and evict the older data).
for example, if we got some data, then a long time (more than what would fit in NMT ram) we don't get any data, and then data again. we might as well hold on to the old data until we need to clear the slot because we received new data maps to that slot.
but if there was no new data (perhaps because a system went down, a probe temporarily disabled itself, whatever) there is no need to clear the old data, because it wouldn't gain us any memory back.

I could have documented this more explicitly, but so the idea is about keeping as much data as we can, bound by the numchunks and chunkspan directives for purposes of controlling RAM usage (but not forcing out data for the sake of forcing out data), to be able to serve as much data out of RAM as possible and exploiting gaps in data to serve larger queries, possibly removing the need to query cassandra at all in some scenarios.
if we phrase the NMT mission statement as "keep the last numchunks of numspan size for each metric" (which seems reasonable) then we don't need any GC for chunks at all, and just evict on an as-needed basis. though there should probably be a facility to clear out inactive metrics (on an aggmetric basis, not chunk basis)

I saw you did some work around this @woodsaj , i haven't studied all the new code yet, but wanted to make these ideas explicit to see what you think and if you have a different opinion.
the alternative approach (not sure if that's what you're going for) would be a more strict forcing of all chunks in the circular buffer to be the last numchunks chunks, and have gaps if there was missing data.  this could be simpler in code but also adds the need for GC.

Some thoughts re https://github.com/raintank/raintank-metric/pull/42:
* i was surprised that 98b0bf1b0cb70aa819a0a252c51222ca01c2f95b adds more lines than removes
* I see a new feature `periodically scan chunks and close any that have not recieved data in a while` and `chunk has not been written to in a while. Lets persist it`. will this be a problem if the data stream gets interrupted (and points get delayed so that it may take tens of minutes or hours before a new point for a metric arrives)
* i'm concerned about the newly added GC which locks the entire aggmetrics struct for the duration of the entire GC run.  this introduces a delay on queries which scales linearly with the amount of metrics, it's not easy to solve this. this is yet another reason why it's IMHO better to just avoid GC and let data expire naturally.

**Comment by woodsaj** [comment]
The primary purpose of the GC tasks is to handle metrics that are no longer being produced. 

> there is no need to clear the old data, because it wouldn't gain us any memory back.

This doesn't make any sense. How can deleting unused data not free memory?  The memory might not get released back to the kernel, but it does get released back to the GO vm.  When a metric stops receiving new data, the GC task will first persist the unfinished chunk (by the default the GC runs every hour, so if no metric has been received for an hour the chunk is persisted).  If the last saved chunk is more then GC time + (chunkspan * numchunks), then the entire aggmetric is purged from memory.  So if the app is tuned to keep 3 hours of data in memory and the default GC of 1 hour is used, then the aggmetric won't be purged until it hasn't been written to for 5hours.

> it's IMHO better to just avoid GC and let data expire naturally.

Stale metrics *need* to be purged from memory to make way for new metrics.  Once the aggmetric is created (with the circular buffer) it will live forever unless we delete it.  Keeping stale metrics in memory indefinitely just doesnt make any sense.

re #42 

* it might be more lines of code but it is significantly simpler code. Additionally the old code used the app start_time to calculate things which could be used any more after the save/load at stop/start time was added.
* It may impact this, but the worst case scenario is that a few metrics will be rejected due to the last chunk being forcefully finished and persisted to disk. And even then this can be addressed pretty easily.
* Yes there is definitely room for optimizations.  But if we try to make everything perfect before pushing this to production we will be waiting forever.

**Comment by Dieterbe** [comment]
after discussion with AJ, i actually like the new cbuf format. it basically doesn't map chunks to given positions by modulo'ing the t0's. rather it just appends at the end and starts over when needed. this gracefully handles gaps. and indeed, the new code is more elegant and simple.
and keeping older data as long as we don't need to clear/reuse their slots also simply follows out of this design, with a configurable setting for when "too old really is too old" :+1:
