### ISSUE TITLE
grafana alerting does not work with new metric-tank

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-metric#89]
the alerting queries sent to metric-tank respond with

```
minDataPoints/maxDataPoints cannot be honored with the series requested
```

**Comment by woodsaj** [comment]
@Dieterbe this looks to be due to 
https://github.com/raintank/raintank-metric/blob/master/metric_tank/http.go#L58

I guess that the query is failing as it is trying to find a solution that has at least 80 points (default maxDataPoints is set to 800).

**Comment by woodsaj** [comment]
@Dieterbe i have committed a change to set the default minDataPoints to 0. Though leaving this open so you can review.

**Comment by Dieterbe** [comment]
hmm.
you nailed the problem but i think the solution could be better.

1) imagine a request like `to=now&from=-30s&maxdataPoints=2000`. with a series with step 10.  perfectly legitimate request, graphite-web would handle it fine, but we would force ourselves to come up with >=200 points even though the request is satisfied by only a few points.
2) what if there's no points at all? in 34f7efc0dda330619d7bd11e06f8e31534eca80b you updated minDP to 1. but maybe a request is just silly (like requesting a small range in between 2 points) but can be validly served by an empty array.

I'm tinking we should go in either of these directions:
1) try harder making sure minDataPoints is reasonable, by considering request range, step, etc.
2) make minDataPoints more of a guideline rather than a hard limit.
3) make minDataPoints an option that is only ever set by providing it in the request, just like maxDataPoints, so we don't work ourselves into these weird corners. But then we are basically asking grafana to implement a non-standard thing. (or ping graphite upstream and they may implement it as well)

I think 2 gets complicated and still too ambiguous (what is the optimal value, how do we handle the multiple cases we now introduce).  I think 1 should be fairly easy to implement (and solves both cases i mentioned), 3 can later still be done as an addition to 1.

**Comment by woodsaj** [comment]
I generally dont like the idea of a minDataPoints variable and i think the best option is to just get rid of it.

The alignRequests() function is far to complex.  We need to strip it down considerably. We will also need to extend the logic to use the retention of each aggregation once https://github.com/raintank/raintank-metric/issues/82 is implemented.  eg if you request a 2month period then raw is not an option as its retention is only 1month.

I should have a PR ready with a slimmed down approach on monday.

**Comment by woodsaj** [comment]
OK PR submitted.  There is still more work to be done to clean out the ramSpan argument being passed in to alignRequests()

The new logic is much simpler and more then 100x faster.

Though the existing logic had some nice features, like preferencing in-memory data over fetching from Cassandra, the complexity was just way to high to lead to any benefit.  Additionally, the performance bottleneck of this application is going to be CPU.  Calling out to Cassandra to get aggregated data is going to yield far superior performance to performing runtime consolidation of large spans of data in memory.

**Comment by woodsaj** [comment]
@Dieterbe any objections to me merging PR #93

**Comment by woodsaj** [comment]
This was merged.

**Comment by Dieterbe** [comment]
for the record, i like that we got rid of the mindatapoints stuff. we were forcing ourself into extra complications for no good reason.
