### ISSUE TITLE
major performance issues with metric-tank in production

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-metric#94]
With so many series in production (~350k) we are seeing performance issues saving chunks to cassandra.

To save a chunk, a new goroutine is created that persists until the chunk is saved.  As all chunks are saved at the same interval, all goroutines are created at about the same time.

Once aggregation is enabled in production the number of series will grow drastically, 5 new series are created for each aggregation. So with an aggSetting of "600:21600:2,7200:21600:2,21600:21600:2" , the number of series will grow from 350k to 5.6million.   
- on every 6th hour, 5.6million chunks will be saved.

Due to all chunks being persisted at the same time, we need to change the way we persist metrics so that we dont need to have 5.6 million goroutines running at the same time.

**Comment by woodsaj** [comment]
I think the best approach is to use a set of worker goroutines for writing to cassandra and use channels to pass chunks in.

**Comment by ctdk** [comment]
I've been thinking about this since the weekend, since dev metric tank has also been having trouble where all the memory on a machine gets gobbled up. I think that sounds like a good way to do it. Have you already started this?

On January 4, 2016, at 8:25 PM, Anthony Woods <notifications@github.com> wrote:

I think the best approach is to use a set of worker goroutines for writing to cassandra and use channels to pass chunks in.

**Comment by woodsaj** [comment]
Havent started on this.  We will need to do some prototyping to find the best option.

**Comment by woodsaj** [comment]
This has been addressed with https://github.com/raintank/raintank-metric/pull/95
